#!/usr/bin/env ruby
$LOAD_PATH << File.expand_path("../../lib", __FILE__)
require "rubygems" if RUBY_VERSION < "1.9"


require 'optparse'
require "hipmost"

options = { path: "./data" }
OptionParser.new do |opts|
  opts.banner = <<-BANNER
    Usage: hipmost [options] [rooms...]

    [rooms] must be at least one pair composed by "Hipchat channel name" and "Mattermost team":"Mattermost channel"

    Example: hipmost General Team:"Town Center"
    Another example: hipmost -p data_folder "Orbital Impact" "Orbital Impact":"General"

  BANNER

  opts.on("-p", "--path [PATH]", 'Path to Hipchat data folder (Default: "./data")') do |p|
    options[:path] = p
  end

  opts.on("-v", "--[no-]verbose", "Run verbosely") do |v|
    options[:verbose] = v
  end
end.parse!


rooms      = ARGV
rooms_size = rooms.size

if rooms_size.zero? || (rooms_size % 2).nonzero?
  puts "Need a pair of rooms to migrate"
  exit 1
end

exit Hipmost::CLI.run(options.merge(rooms: rooms))
