#!/usr/bin/env ruby
$LOAD_PATH << File.expand_path("../../lib", __FILE__)
require "rubygems" if RUBY_VERSION < "1.9"


require 'optparse'
require "hipmost"

options = { path: "./data" }
OptionParser.new do |opts|
  opts.banner = <<-BANNER
    Usage: hipmost [options] [command]

    Commands:

    public (AKA, room or rooms)
    Form: public [import|list] [rooms] - Import or list public Hipchat rooms

    [rooms] must be at least one pair composed by "Hipchat channel name" and "Mattermost team":"Mattermost channel"
    The Mattermost team or channel can be the URL endpoint, such as "town-square", or the channel name, such as "General"

    --------

    private (AKA, direct)
    Form: private [import|list]  - Import or list private chats

    --------

    Examples:
    $ hipmost room import "Orbital Impact" "Orbital Impact":"General"
    $ hipmost public import "Orbital Impact" "Orbital Impact":"General" -p data_folder
    $ hipmost private list
    $ hipmost -v rooms import "Orbital Impact" "Orbital Impact":"General"

  BANNER

  opts.on("-p", "--path [PATH]", 'Path to Hipchat data folder (Default: "./data")') do |p|
    options[:path] = p
  end

  opts.on("-v", "--[no-]verbose", "Run verbosely") do |v|
    options[:verbose] = true
  end
end.parse!

command = ARGV.shift

exit Hipmost::CLI.run(command, ARGV, options)
